/*
 * generated by Xtext
 */
package org.xtext.example.hellobuck;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HelloBuckRuntimeModule extends org.xtext.example.hellobuck.AbstractHelloBuckRuntimeModule {

}
