/*
 * generated by Xtext
 */
package org.xtext.example.hellobuck.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HelloBuckUiModule extends org.xtext.example.hellobuck.ui.AbstractHelloBuckUiModule {
	public HelloBuckUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
