/*
 * generated by Xtext
 */
package org.xtext.example.hellobuck.ui.contentassist

import org.xtext.example.hellobuck.ui.contentassist.AbstractHelloBuckProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HelloBuckProposalProvider extends AbstractHelloBuckProposalProvider {
}
