/*
* generated by Xtext
*/
package org.xtext.example.hellobuck.ui.contentassist;

import org.xtext.example.hellobuck.ui.contentassist.AbstractHelloBuckProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class HelloBuckProposalProvider extends AbstractHelloBuckProposalProvider {

}
