/*
* generated by Xtext
*/
package org.xtext.example.hellobuck;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HelloBuckUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.hellobuck.ui.internal.HelloBuckActivator.getInstance().getInjector("org.xtext.example.hellobuck.HelloBuck");
	}
	
}
