/*
 * generated by Xtext
 */
package org.xtext.example.hellobuck.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.hellobuck.ui.internal.HelloBuckActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HelloBuckExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HelloBuckActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HelloBuckActivator.getInstance().getInjector(HelloBuckActivator.ORG_XTEXT_EXAMPLE_HELLOBUCK_HELLOBUCK);
	}
	
}
